feat: Initial project setup
PSW-2021-ORG7/Hospital pull request #1
Opened 2021-10-31 23:11 UTC by racicmelanija

Initial project setup for integration and graphical editor teams.

2021-10-31 23:21 UTC, vujsa7 approved these changes
Remove WeatherForecastController.cs in the future. Everything else is good.

2021-11-01 00:37 UTC, anagavrilovic requested changes
1. The project structure is not like the requested structure. The model directory is supposed to be in the Class Library project. 
2. Working with database: Hospital API is supposed to communicate with Hospital Class Library project (Service or Repository class) and then that class communicates with the database. Therefore, using Entity Framework in the Controller class is questionable, and also Migrations directory needs to be in the Class Library project as well.
3. Delete automatically generated classes.

2021-11-01 13:48 UTC, anagavrilovic approved these changes
Looks good!

2021-11-01 13:51 UTC, vujsa7 approved these changes

2021-11-01 13:53 UTC, merged